const chalk = require("chalk")
const fs = require("fs")

//owmner v card
global.owner = ['6285727507760] //ur owner number
global.ownernomer = "6281215919909" //ur owner number2
global.ownername = "YAHYA STORE" //ur owner name
global.grup = "https://chat.whatsapp.com/HoPAZDBVqzDC3KuMgttS6P" //ur group link
global.socialm = "GitHub: YAHYA STORE " //ur github or insta name
global.location = "Indonesia" //ur location

//payment ----- lu tau lah diubah jadi apaan
global.dana = "085727507760"
global.ovo = "085727507760"
global.gopay = "085727507760"
global.saweria = "-"

//new
global.ownergc = "-"
global.botname = "YAHYA STORE"
global.ownerNumber = ["6285727507760@s.whatsapp.net"]
global.ownerweb = "https://youtube.com/@YAHHA STORE"
global.themeemoji = 'ðŸª€'
global.wm = "store.yahya.link"
global.packname = "Sticker By"
global.author = "Yahya\n\n"
global.prefa = ['','!','.','#','&']
global.sessionName = 'session'
global.tekspushkon = 'pushkontak SV YAHYA STORE
global.keyopenai ='iigf'

global.domain = 'https://' // Isi Domain Lu
global.apikey = '' // Isi Apikey Plta Lu
global.capikey = '' // Isi Apikey Pltc Lu
global.eggsnya = '15' // id eggs yang dipake
global.location = '1' // id location

global.limitawal = {
    premium: "Infinity",
    free: 5
}

//media target
global.thumbmenu ='https://telegra.ph/file/3a8e30f86ad9377cf0689.png'

global.thumb = { url: 'https://telegra.ph/file/26e0f1f23a416a4261b73.jpg' }
global.defaultpp = 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png?q=60' //default pp wa

//messages
global.mess = {
    selesai: 'Done !!', 
    owner: 'Khusus Owner',
    private: 'Khusus Private',
    group: 'Khusus Group',
    wait: 'Sebentar..',
}

global.listharga = `ð—Ÿð—œð—¦ð—§ ð—›ð—”ð—¥ð—šð—” ð—©ð—£ð—¦ ð—•ð—¬ ð—¥ð—¬ð—¡ð—«ð——ðŸ”¥

Ram 1 Core 1 per bulan : 20k
Ram 2 Core 1 per bulan : 30k
Ram 4 Core 2 per bulan : 45k
Ram 6 Core 4 per bulan : 60k

ð—Ÿð—œð—¦ð—§ ð—›ð—”ð—¥ð—šð—” ð—£ð—”ð—¡ð—˜ð—Ÿ ð—¥ð—¨ð—¡ ð—•ð—¢ð—§ðŸ”¥

ð—£ð—”ð—žð—˜ð—§ ð— ð—¨ð—¥ð—”ð—› :
1GB RAM 30% CPU : 3k
2GB RAM 50%CPU : 5k
3GB RAM 80% CPU : 6k
4GB RAM 100% CPU : 7k
5GB RAM 120% CPU: 8k
6GB RAM 150% CPU: 9k
7GB RAM 180% CPU : 10k
8GB RAM 200% CPU: 11k
9GB RAM 230% CPU : 12k
10GB RAM 250% CPU : 13k

ð—£ð—”ð—žð—˜ð—§ ð—Ÿð—”ð—œð—¡ð—¡ð—¬ð—” :
UNLI RAM UNLI CPU : 15k
ADMIN PANEL : 30k
`

let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update'${__filename}'`))
	delete require.cache[file]
	require(file)
